name: project_template
description: Starting template for a new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #* UI
  cached_network_image: ^3.2.2
  flash: ^2.0.5
  flutter_keyboard_visibility: ^5.3.0
  google_fonts: ^3.0.1

  #* Icons
  flutter_vector_icons: ^2.0.0

  #* Firebase
  firebase_analytics: ^9.3.7
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.8.12
  firebase_messaging: ^13.0.4

  #* Local notification
  awesome_notifications: ^0.7.0+1

  #* Network
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1

  #* Dart data class
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0

  #* Dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  #* State management
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1

  #* Logging
  logging: ^1.0.2

  #* Routing
  auto_route: ^5.0.1

  #* Persistent storage
  flutter_secure_storage: ^6.0.0
  hive_flutter: ^1.1.0

  #* Localization
  intl: ^0.17.0

  #* Date Time util
  jiffy: ^5.0.0

  #* Misc
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Code generators
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.10+1
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.4.1

  #* Test
  bloc_test: ^9.1.0
  mocktail: ^0.3.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true